language: ruby

rvm:
  - 2.0.0
  - 2.1.5
  - 2.2.1
  - 2.2.2
  - 2.2.3

before_install:
  - export NOKOGIRI_USE_SYSTEM_LIBRARIES=true

install:
  - npm update
  - npm install -g grunt-cli

script:
  - grunt build

branches:
  only:
    - gh-pages

notifications:
  email: false

sudo: false

after_install:
  - grunt install
  - grunt test
