language: ruby

rvm:
  - 2.0.0
  - 2.1.5
  - 2.2.1
  - 2.2.2

before_install:
  - export NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - npm install -g grunt-cli

install:

  - npm install npm@latest
  - grunt install

script:
  - grunt build

branches:
  only:
    - gh-pages

notifications:
  email: false

sudo: true

after_install:
  - grunt test
